#!/bin/sh

# set this to workaround expr problems in shFlags on freebsd
if uname -s | egrep -iq 'bsd'; then export EXPR_COMPAT=1; fi

# enable debug mode
if [ "$DEBUG" = "yes" ]; then
	set -x
fi

# The sed expression here replaces all backslashes by forward slashes.
# This helps our Windows users, while not bothering our Unix users.
export GITSCRUM_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

usage() {
	echo "usage: git scrum <subcommand>"
	echo
	echo "Available subcommands are:"
	echo "   init       Initialize a new git repo with support for the branching model."
	echo "   sprint     Manage your sprint branches."
	echo "   task       Manage your task branches of the sprint."
	echo "   release    Manage your release branches."
	echo "   hotfix     Manage your hotfix branches."
	echo "   support    Manage your support branches."
	echo "   version    Shows version information."
	echo
	echo "Try 'git scrum <subcommand> help' for details."
}

main() {
	if [ $# -lt 1 ]; then
		usage
		exit 1
	fi

	# load common functionality
	. "$GITSCRUM_DIR/gitscrum-common"

	# This environmental variable fixes non-POSIX getopt style argument
	# parsing, effectively breaking git-scrum subcommand parsing on several
	# Linux platforms.
	export POSIXLY_CORRECT=1

	# use the shFlags project to parse the command line arguments
	. "$GITSCRUM_DIR/gitscrum-shFlags"
	FLAGS_PARENT="git scrum"

  # allow user to request git action logging
  DEFINE_boolean show_commands false 'show actions taken (git commands)' g

  # do actual parsing
	FLAGS "$@" || exit $?
	eval set -- "${FLAGS_ARGV}"

	# sanity checks
	SUBCOMMAND="$1"; shift

	if [ ! -e "$GITSCRUM_DIR/git-scrum-$SUBCOMMAND" ]; then
		usage
		exit 1
	fi

	# run command
	. "$GITSCRUM_DIR/git-scrum-$SUBCOMMAND"
	FLAGS_PARENT="git scrum $SUBCOMMAND"

	# test if the first argument is a flag (i.e. starts with '-')
	# in that case, we interpret this arg as a flag for the default
	# command
	SUBACTION="default"
	if [ "$1" != "" ] && { ! echo "$1" | grep -q "^-"; } then
		SUBACTION="$1"; shift
	fi
	if ! type "cmd_$SUBACTION" >/dev/null 2>&1; then
		warn "Unknown subcommand: '$SUBACTION'"
		usage
		exit 1
	fi

  if [ $SUBACTION != "help" ] && [ $SUBCOMMAND != "init" ] ; then
    init
  fi
  cmd_$SUBACTION "$@"
}

main "$@"
